spring.application.name=lab65-batch-migration
spring.config.import=optional:file:.env[.properties]

lab65-batch-migration.rds_endpoint=${RDS_ENDPOINT}
lab65-batch-migration.db_secret_arn=${DB_SECRET_ARN}