spring.application.name=lab6-rds

server.port=8080

# Fine for labs. In prod you should use Flyway/Liquibase migrations.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,metrics